quarkus.http.port=9090
quarkus.package.type=uber-jar
quarkus.http.limits.max-form-attribute-size=4M
quarkus.jackson.timezone=Asia/Kolkata


#Swagger config
quarkus.smallrye-openapi.path=/swagger
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=EKYC
quarkus.smallrye-openapi.info-version=0.0.1

#hazlecast	
#config.app.hazel.cluster=codifi
config.app.hazel.cluster=dev
config.app.hazel.address=127.0.0.1:5701
config.app.hazel.for=dev



#Db config
quarkus.datasource.db-kind=mysql
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.dialect=org.hibernate.dialect.MySQL8Dialect
quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.packages=in.codifi.ambalal.entity


#Encryption Key for filter
appconfig.token.encryption.key=8526707787codifi1234567cholaekyc

#JDBC Primary
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/payment_live?rewriteBatchedStatements=true&useSSL=false&allowPublicKeyRetrieval=true
#quarkus.datasource.jdbc.url=jdbc:mysql://13.202.121.144:3306/payment_live
quarkus.datasource.username=root
quarkus.datasource.password=St0ne@ge@202!

#GLOBE
quarkus.rest-client.config-globe.url=https://AllocAPI.globecapital.in/
quarkus.rest-client.logging.scope=request-response
#RMS
quarkus.rest-client.config-aecor.url=https://online.aecorcapitalplus.com/
#TECH EXCEL 
quarkus.rest-client.config-techexcel.url=https://ho.ambalalshares.com:8643/TechBoRest/api/


#LIVE LOGS TABLE
quarkus.datasource.logs.jdbc.url=jdbc:mysql://localhost:3306/payment_live_logs?rewriteBatchedStatements=true&useSSL=false&allowPublicKeyRetrieval=true
#quarkus.datasource.logs.jdbc.url=jdbc:mysql://13.202.121.144:3306/payment_live_logs?rewriteBatchedStatements=true&useSSL=false&allowPublicKeyRetrieval=true
quarkus.datasource.logs.username=root
quarkus.datasource.logs.password=St0ne@ge@202!
appconfig.log.db.name=payment_live_logs


#Logs Database properties
quarkus.datasource.logs.db-kind=mysql
quarkus.hibernate-orm.logs.database.generation=none
quarkus.hibernate-orm.logs.datasource=logs
quarkus.datasource.logs.jdbc.max-size=250
quarkus.datasource.logs.jdbc.min-size=1
quarkus.datasource.logs.jdbc.max-lifetime=60000
quarkus.datasource.logs.jdbc.validation-query-sql=SELECT 1
quarkus.hibernate-orm.logs.physical-naming-strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
quarkus.hibernate-orm.logs.implicit-naming-strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
quarkus.hibernate-orm.logs.packages=in.codifi.ambalal.entity.logs

appconfig.file.basepath=/opt/files/payin/docs/